version: '3.8'

services:
  db:
    container_name: ${PSQL_HOST}
    image: postgres:15.1
    environment:
      POSTGRES_DB: ${PSQL_DB}
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - pgsql_data:/var/lib/postgresql/data/
    networks:
      - internship_network

  redis:
    container_name: ${REDIS_HOST}
    image: redis:latest
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - '6379:6379'
    volumes:
      - ./redis-data:/var/lib/redis/data/
    networks:
      - internship_network

  backend:
    container_name: internship_backend
    build: ./
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    depends_on:
      - db
      - redis
    networks:
      - internship_network

volumes:
  pgsql_data:

networks:
  internship_network:
    name: internship_network
    driver: bridge
