# Generated by Django 4.2.5 on 2023-10-24 10:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_companymember_admin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('correct_answers', models.FloatField(default=0, verbose_name='correct answers')),
                ('total_questions', models.PositiveIntegerField(default=0, verbose_name='total questions')),
                ('progress_status', models.CharField(choices=[('STARTED', 'started'), ('COMPLETED', 'completed')], default='started', verbose_name='progress status')),
                ('correct_answers_collector', models.FloatField(default=0, verbose_name='correct answers collector')),
                ('total_questions_collector', models.PositiveIntegerField(default=0, verbose_name='total questions collector')),
                ('correct_company_answers_collector', models.FloatField(default=0, verbose_name='correct company answers collector')),
                ('total_company_questions_collector', models.PositiveIntegerField(default=0, verbose_name='total company questions collector')),
                ('quiz_time', models.DurationField(default=datetime.timedelta(0), verbose_name='quiz time')),
                ('company_average_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='company average score')),
                ('user_rating', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='user rating')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_company_result', to='company.company', verbose_name='company')),
                ('participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_participant_result', to=settings.AUTH_USER_MODEL, verbose_name='participant')),
                ('quiz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_result', to='quiz.quiz', verbose_name='quiz')),
            ],
            options={
                'verbose_name': 'user quiz result',
                'verbose_name_plural': 'user quiz results',
            },
        ),
    ]
