# Generated by Django 4.2.5 on 2023-10-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_options_invitationtocompany_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymember',
            name='admin',
            field=models.BooleanField(default=False, verbose_name='admin'),
        ),
    ]
