# Generated by Django 4.2.5 on 2023-10-07 00:47

from django.db import migrations, models
import functools
import services.get_file_path


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=functools.partial(services.get_file_path.get_path_with_unique_filename, *(), **{'file_path': 'images/users/avatars'}), verbose_name='avatar'),
        ),
    ]
