name: Deployment to AWS

on:
  pull_request:
    branches: BE-code-review
    types: closed

jobs:
  deployment:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python3.11 -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create .env file
      run: |
        touch .env
        echo "${{ secrets.PROD_ENV_FILE }}" > .env

    - name: Restart Supervisor
      run: sudo supervisorctl restart internship_meduzzen_backend

    - name: Restart Nginx
      run: sudo service nginx restart
