name: Meduzzen backend CI/CD

env:
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  DEBUG: ${{ secrets.DEBUG }}
  DJANGO_ALLOWED_HOSTS: ${{ secrets.DJANGO_ALLOWED_HOSTS }}

  PSQL_DB: ${{ secrets.PSQL_DB }}
  PSQL_NAME: ${{ secrets.PSQL_NAME }}
  PSQL_USER: ${{ secrets.PSQL_USER }}
  PSQL_PASSWORD: ${{ secrets.PSQL_PASSWORD }}
  PSQL_HOST: ${{ secrets.PSQL_HOST }}
  PSQL_PORT: ${{ secrets.PSQL_PORT }}

  REDIS_HOST: ${{ secrets.REDIS_HOST }}
  REDIS_PORT: ${{ secrets.REDIS_PORT }}
  REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
  REDIS_DB: ${{ secrets.REDIS_DB }}

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - 'develop'

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: ${{ secrets.PSQL_DB }}
          POSTGRES_NAME: ${{ secrets.PSQL_NAME }}
          POSTGRES_USER: ${{ secrets.PSQL_USER }}
          POSTGRES_PASSWORD: ${{ secrets.PSQL_PASSWORD }}
          POSTGRES_HOST: ${{ secrets.PSQL_HOST }}
          POSTGRES_PORT: ${{ secrets.PSQL_PORT }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:latest
        env:
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
          REDIS_DB: ${{ secrets.REDIS_DB }}
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run migrations
      run: python manage.py migrate

    - name: Run tests
      run: python manage.py test

    - name: Run linters
      run: ruff check .
